title: 'Sistemas y Tecnologías Web: Servidor'
subtitle: 'Master de Ingeniería Informática'
#remote_theme: mmistakes/minimal-mistakes
#minimal_mistakes_skin: "plum" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
theme: jekyll-theme-midnight
description: 'Master de II. ULL. 1er cuatrimestre. 2019/2020'
exclude: 
  - node_modules
  - tema3-web/practicas/p10-t3-commanding-databases/eval
show_downloads: false
live_reload: true
collections: 
  practicas: 
    order: 
      - 01p01-t1-iaas.md
      - 02p2-t1-vscode.md
      - 03p2-t1-c3-file-system.md
      - 04p3-t1-c3-http.md
      - 05p4-t2-networking.md
      - 06p5-t3-websockets.md
      - 07p9-t3-transforming-data.md
      - 08p8-t3-jekyll-netlify.md
      - 09p10-t3-commanding-databases.md
    output: true
campus_virtual: https://campusvirtual.ull.es/1920/mod/assign/index.php?id=201913778
calificador: https://campusvirtual.ull.es/1920/grade/report/grader/index.php?id=201913778
github_org: https://github.com/ULL-MII-SYTWS-1920
repo_apuntes: https://github.com/ULL-MII-SYTWS-1920/ull-mii-sytws-1920.github.io/
despliegue_apuntes: https://ull-mii-sytws-1920.github.io/
classroom: https://classroom.github.com/classrooms/55384072-master-de-ingenieria-informatica-sistemas-y-tecnologias-web-servidor-classroom
profesor: https://www.ull.es/apps/guias/guias/view_teacher_niu/588/(%3FPcrguezl.*)/
profesor_name: Casiano
acronimo: SYTWS
acronimo_curso: SYTWS 19/20
comments: true
disqus: https://https-ull-mii-sytws-1920-github-io.disqus.com/embed.js
bull_permanente: https://puntoq.ull.es/permalink/f
temas:
  - path: tema0-presentacion
    title: "Tema 0: Presentación"
  - path: tema1-introduccion
    title: "Tema 1: Introducción"
  - path: tema2-async
    title: "Tema 2: Computación Asíncrona y Distribuída"
  - path: tema3-web
    title: "Tema 3: Servicios y Aplicaciones Web"
  - path: tema4-devops
    title: "Tema 4: DevOps"
