title: 'Sistemas y Tecnologías Web: Servidor'
subtitle: 'Master de Ingeniería Informática'
theme: jekyll-theme-midnight
description: '1er cuatrimestre. ULL. Curso 2019/2020'
exclude: 
  - node_modules
  - tema3-web/practicas/p10-t3-commanding-databases/eval
show_downloads: false
campus_virtual: https://campusvirtual.ull.es/1920/mod/assign/index.php?id=201913778