title: 'Tecnologías Web: Back End'
subtitle: 'Master de Ingeniería Informática'
theme: jekyll-theme-midnight
description: '1er cuatrimestre. ULL. Curso 2019/2020'
exclude: [ 'Arona-winter-course', 'dsi1819', 'dsi1819-introduccion', 'tema0-introduccion-a-pl/practicas/code']
show_downloads: false