title: 'Sistemas y Tecnologías Web: Servidor'
subtitle: 'Master de Ingeniería Informática'
theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "plum" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
#theme: jekyll-theme-midnight
description: '1er cuatrimestre. ULL. Curso 2019/2020'
exclude: 
  - node_modules
  - tema3-web/practicas/p10-t3-commanding-databases/eval
show_downloads: false
live_reload: true
campus_virtual: https://campusvirtual.ull.es/1920/mod/assign/index.php?id=201913778
github_org: https://github.com/ULL-MII-SYTWS-1920
repo_apuntes: https://github.com/ULL-MII-SYTWS-1920/ull-mii-sytws-1920.github.io/
despliegue_apuntes: https://ull-mii-sytws-1920.github.io/
classroom: https://classroom.github.com/classrooms/55384072-master-de-ingenieria-informatica-sistemas-y-tecnologias-web-servidor-classroom
profesor: https://www.ull.es/apps/guias/guias/view_teacher_niu/588/(%3FPcrguezl.*)/
profesor_name: Casiano
acronimo: SYTWS
acronimo_curso: SYTWS 19/20
comments: true
disqus: https://https-ull-mii-sytws-1920-github-io.disqus.com/embed.js