title: 'Desarrollo y Mantenimiento de Sistemas Informáticos'
subtitle: 'Itinerario de Sistemas de la Información. Grado en Ingeniería Informática. ULL. Curso 2019/2020'
theme: jekyll-theme-midnight
description: '4º. 1er cuatrimestre. Itinerario de Sistemas de la Información. Grado en Ingeniería Informática. ULL. Curso 2019/2020'
exclude: [ 'Arona-winter-course', 'dsi1819', 'dsi1819-introduccion', 'tema0-introduccion-a-pl/practicas/code']
show_downloads: false