title: 'Sistemas y Tecnologías Web: Servidor'
subtitle: 'Master de Ingeniería Informática'
#remote_theme: mmistakes/minimal-mistakes
#minimal_mistakes_skin: "plum" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
theme: jekyll-theme-midnight
description: 'Master de II. ULL. 1er cuatrimestre. 2020/2021'
future: true
exclude: 
  - node_modules
  - tema3-web/practicas/p10-t3-commanding-databases/eval
  - tema2-async/practicas/p7-t2-asyncmap/sol-reto-async-reading-multiple-files
  - tema2-async/practicas/p9-t2-promise-readfile/solution
  - tema2-async/practicas/p10-t2-promise-all/solution
show_downloads: false
live_reload: true
organization: 
  url: https://github.com/ULL-MII-SYTWS-2021
  name: ULL-MII-SYTWS-2021
  master: https://github.com/ULL-MII-SYTWS-2021/tree/master/
chat: https://chat.google.com/u/1/room/AAAAp18fCE8
classroom:
  url: https://classroom.github.com/classrooms/68184806-ull-mii-sytws-2021
  name: ULL-MII-SYTWS-2021
collections: 
  practicas: 
    order: 
      - 01p01-t1-iaas.md
      - 02p2-t1-vscode.md
      - 03p2-t1-c3-file-system.md
      - 05p5-t1-meta.md
      - 06p6-t1-gh-cli.md
      #- 04p3-t1-c3-http.md
      #- 05p4-t2-networking.md
      #- 06p5-t3-websockets.md
      #- 07p9-t3-transforming-data.md
      #- 08p8-t3-jekyll-netlify.md
      #- 09p10-t3-commanding-databases.md
      #- 10p10-t3-jekyll-search.md
    output: true
campus_virtual:
  home: https://campusdoctoradoyposgrado.ull.es/course/view.php?id=2020111300 
  tareas: https://campusdoctoradoyposgrado.ull.es/mod/assign/index.php?id=2020111300
calificador: https://campusdoctoradoyposgrado.ull.es/grade/report/grader/index.php?id=2020111300
covid_ull: https://campusvirtual.ull.es/doctoradoyposgrado/course/view.php?id=201913946
horarios_tutorias: https://docs.google.com/spreadsheets/d/1ZTGvLA70qCYEsBwcA8dCiUZby3ZOM9oHt8kmiNNKId0/edit#gid=0
github_org: https://github.com/ULL-MII-SYTWS-2021
repo_apuntes: https://github.com/ULL-MII-SYTWS-1920/ull-mii-sytws-1920.github.io/
repo_url_master: https://github.com/ULL-MII-SYTWS-1920/ull-mii-sytws-1920.github.io/tree/master/
despliegue_apuntes: https://ull-mii-sytws-1920.github.io/
#classroom: https://classroom.github.com/classrooms/55384072-master-de-ingenieria-informatica-sistemas-y-tecnologias-web-servidor-classroom
profesor: https://www.ull.es/apps/guias/guias/view_teacher_niu/745/(%3FPcrguezl.*)/
profesor_name: Casiano
acronimo: SYTWS
acronimo_curso: SYTWS 19/20
comments: true
start_date: "September 28, 2020"
disqus: https://https-ull-mii-sytws-1920-github-io.disqus.com/embed.js
bull_permanente: https://puntoq.ull.es/permalink/f
temas:
  - path: tema0-presentacion
    title: "Tema 0: Presentación"
  - path: tema1-introduccion
    title: "Tema 1: Introducción"
  - path: tema2-async
    title: "Tema 2: Computación Asíncrona y Distribuída"
  - path: tema3-web
    title: "Tema 3: Servicios y Aplicaciones Web"
  - path: tema4-devops
    title: "Tema 4: DevOps"
books_shared: https://github.com/ULL-MII-SYTWS-2021/books-shared/tree/master/
books_shared_2019: https://github.com/ULL-MII-SYTWS-1920/books-shared/tree/master/
meet: https://meet.google.com/bhv-togn-ynm